//
// AkaliChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AkaliChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var akali: ChampionDetailObj

    public init(akali: ChampionDetailObj) {
        self.akali = akali
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case akali = "Akali"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(akali, forKey: .akali)
    }
}

