//
// AkshanChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AkshanChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var akshan: ChampionDetailObj

    public init(akshan: ChampionDetailObj) {
        self.akshan = akshan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case akshan = "Akshan"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(akshan, forKey: .akshan)
    }
}

