//
// AlistarChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AlistarChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var alistar: ChampionDetailObj

    public init(alistar: ChampionDetailObj) {
        self.alistar = alistar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alistar = "Alistar"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(alistar, forKey: .alistar)
    }
}

