//
// AmumuChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AmumuChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var amumu: ChampionDetailObj

    public init(amumu: ChampionDetailObj) {
        self.amumu = amumu
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amumu = "Amumu"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amumu, forKey: .amumu)
    }
}

