//
// AniviaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AniviaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var anivia: ChampionDetailObj

    public init(anivia: ChampionDetailObj) {
        self.anivia = anivia
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case anivia = "Anivia"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(anivia, forKey: .anivia)
    }
}

