//
// AnnieChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnnieChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var annie: ChampionDetailObj

    public init(annie: ChampionDetailObj) {
        self.annie = annie
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case annie = "Annie"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(annie, forKey: .annie)
    }
}

