//
// AsheChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AsheChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var ashe: ChampionDetailObj

    public init(ashe: ChampionDetailObj) {
        self.ashe = ashe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ashe = "Ashe"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ashe, forKey: .ashe)
    }
}

