//
// AurelionSolChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AurelionSolChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var aurelionSol: ChampionDetailObj

    public init(aurelionSol: ChampionDetailObj) {
        self.aurelionSol = aurelionSol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aurelionSol = "AurelionSol"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aurelionSol, forKey: .aurelionSol)
    }
}

