//
// BardChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BardChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var bard: ChampionDetailObj

    public init(bard: ChampionDetailObj) {
        self.bard = bard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bard = "Bard"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bard, forKey: .bard)
    }
}

