//
// BelvethChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BelvethChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var belveth: ChampionDetailObj

    public init(belveth: ChampionDetailObj) {
        self.belveth = belveth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case belveth = "Belveth"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(belveth, forKey: .belveth)
    }
}

