//
// BlitzcrankChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BlitzcrankChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var blitzcrank: ChampionDetailObj

    public init(blitzcrank: ChampionDetailObj) {
        self.blitzcrank = blitzcrank
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blitzcrank = "Blitzcrank"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blitzcrank, forKey: .blitzcrank)
    }
}

