//
// BraumChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BraumChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var braum: ChampionDetailObj

    public init(braum: ChampionDetailObj) {
        self.braum = braum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case braum = "Braum"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(braum, forKey: .braum)
    }
}

