//
// BriarChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BriarChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var briar: ChampionDetailObj

    public init(briar: ChampionDetailObj) {
        self.briar = briar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case briar = "Briar"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(briar, forKey: .briar)
    }
}

