//
// CaitlynChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CaitlynChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var caitlyn: ChampionDetailObj

    public init(caitlyn: ChampionDetailObj) {
        self.caitlyn = caitlyn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case caitlyn = "Caitlyn"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(caitlyn, forKey: .caitlyn)
    }
}

