//
// CamilleChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CamilleChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var camille: ChampionDetailObj

    public init(camille: ChampionDetailObj) {
        self.camille = camille
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case camille = "Camille"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(camille, forKey: .camille)
    }
}

