//
// CassiopeiaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CassiopeiaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var cassiopeia: ChampionDetailObj

    public init(cassiopeia: ChampionDetailObj) {
        self.cassiopeia = cassiopeia
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cassiopeia = "Cassiopeia"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cassiopeia, forKey: .cassiopeia)
    }
}

