//
// ChampionDetailObjSkinsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChampionDetailObjSkinsInner: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var num: Double?
    public var name: String?
    public var chromas: Bool?

    public init(id: String? = nil, num: Double? = nil, name: String? = nil, chromas: Bool? = nil) {
        self.id = id
        self.num = num
        self.name = name
        self.chromas = chromas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case num
        case name
        case chromas
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(num, forKey: .num)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(chromas, forKey: .chromas)
    }
}

