//
// ChampionDetailData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChampionDetailData: Codable, JSONEncodable, Hashable {

    public var type: String
    public var format: String
    public var version: String
    public var data: ChampionDetailDataData

    public init(type: String, format: String, version: String, data: ChampionDetailDataData) {
        self.type = type
        self.format = format
        self.version = version
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case format
        case version
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(format, forKey: .format)
        try container.encode(version, forKey: .version)
        try container.encode(data, forKey: .data)
    }
}

