//
// ChogathChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChogathChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var chogath: ChampionDetailObj

    public init(chogath: ChampionDetailObj) {
        self.chogath = chogath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chogath = "Chogath"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chogath, forKey: .chogath)
    }
}

