//
// CorkiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CorkiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var corki: ChampionDetailObj

    public init(corki: ChampionDetailObj) {
        self.corki = corki
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case corki = "Corki"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(corki, forKey: .corki)
    }
}

