//
// DariusChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DariusChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var darius: ChampionDetailObj

    public init(darius: ChampionDetailObj) {
        self.darius = darius
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case darius = "Darius"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(darius, forKey: .darius)
    }
}

