//
// DianaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DianaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var diana: ChampionDetailObj

    public init(diana: ChampionDetailObj) {
        self.diana = diana
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case diana = "Diana"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(diana, forKey: .diana)
    }
}

