//
// DravenChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DravenChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var draven: ChampionDetailObj

    public init(draven: ChampionDetailObj) {
        self.draven = draven
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case draven = "Draven"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(draven, forKey: .draven)
    }
}

