//
// DrMundoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DrMundoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var drMundo: ChampionDetailObj

    public init(drMundo: ChampionDetailObj) {
        self.drMundo = drMundo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case drMundo = "DrMundo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(drMundo, forKey: .drMundo)
    }
}

