//
// EkkoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EkkoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var ekko: ChampionDetailObj

    public init(ekko: ChampionDetailObj) {
        self.ekko = ekko
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ekko = "Ekko"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ekko, forKey: .ekko)
    }
}

