//
// EliseChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EliseChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var elise: ChampionDetailObj

    public init(elise: ChampionDetailObj) {
        self.elise = elise
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elise = "Elise"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(elise, forKey: .elise)
    }
}

