//
// EvelynnChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EvelynnChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var evelynn: ChampionDetailObj

    public init(evelynn: ChampionDetailObj) {
        self.evelynn = evelynn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case evelynn = "Evelynn"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(evelynn, forKey: .evelynn)
    }
}

