//
// FiddlesticksChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FiddlesticksChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var fiddlesticks: ChampionDetailObj

    public init(fiddlesticks: ChampionDetailObj) {
        self.fiddlesticks = fiddlesticks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fiddlesticks = "Fiddlesticks"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fiddlesticks, forKey: .fiddlesticks)
    }
}

