//
// GalioChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GalioChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var galio: ChampionDetailObj

    public init(galio: ChampionDetailObj) {
        self.galio = galio
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case galio = "Galio"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(galio, forKey: .galio)
    }
}

