//
// GarenChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GarenChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var garen: ChampionDetailObj

    public init(garen: ChampionDetailObj) {
        self.garen = garen
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case garen = "Garen"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(garen, forKey: .garen)
    }
}

