//
// GragasChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GragasChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var gragas: ChampionDetailObj

    public init(gragas: ChampionDetailObj) {
        self.gragas = gragas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gragas = "Gragas"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gragas, forKey: .gragas)
    }
}

