//
// GwenChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GwenChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var gwen: ChampionDetailObj

    public init(gwen: ChampionDetailObj) {
        self.gwen = gwen
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gwen = "Gwen"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gwen, forKey: .gwen)
    }
}

