//
// IllaoiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IllaoiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var illaoi: ChampionDetailObj

    public init(illaoi: ChampionDetailObj) {
        self.illaoi = illaoi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case illaoi = "Illaoi"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(illaoi, forKey: .illaoi)
    }
}

