//
// InfoObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InfoObj: Codable, JSONEncodable, Hashable {

    public var attack: Double
    public var defense: Double
    public var magic: Double
    public var difficulty: Double

    public init(attack: Double, defense: Double, magic: Double, difficulty: Double) {
        self.attack = attack
        self.defense = defense
        self.magic = magic
        self.difficulty = difficulty
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attack
        case defense
        case magic
        case difficulty
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attack, forKey: .attack)
        try container.encode(defense, forKey: .defense)
        try container.encode(magic, forKey: .magic)
        try container.encode(difficulty, forKey: .difficulty)
    }
}

