//
// IreliaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IreliaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var irelia: ChampionDetailObj

    public init(irelia: ChampionDetailObj) {
        self.irelia = irelia
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case irelia = "Irelia"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(irelia, forKey: .irelia)
    }
}

