//
// IvernChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IvernChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var ivern: ChampionDetailObj

    public init(ivern: ChampionDetailObj) {
        self.ivern = ivern
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ivern = "Ivern"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ivern, forKey: .ivern)
    }
}

