//
// JannaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JannaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var janna: ChampionDetailObj

    public init(janna: ChampionDetailObj) {
        self.janna = janna
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case janna = "Janna"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(janna, forKey: .janna)
    }
}

