//
// JayceChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JayceChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var jayce: ChampionDetailObj

    public init(jayce: ChampionDetailObj) {
        self.jayce = jayce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jayce = "Jayce"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jayce, forKey: .jayce)
    }
}

