//
// JhinChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JhinChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var jhin: ChampionDetailObj

    public init(jhin: ChampionDetailObj) {
        self.jhin = jhin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jhin = "Jhin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jhin, forKey: .jhin)
    }
}

