//
// JinxChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JinxChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var jinx: ChampionDetailObj

    public init(jinx: ChampionDetailObj) {
        self.jinx = jinx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jinx = "Jinx"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jinx, forKey: .jinx)
    }
}

