//
// KaisaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KaisaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kaisa: ChampionDetailObj

    public init(kaisa: ChampionDetailObj) {
        self.kaisa = kaisa
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kaisa = "Kaisa"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kaisa, forKey: .kaisa)
    }
}

