//
// KalistaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KalistaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kalista: ChampionDetailObj

    public init(kalista: ChampionDetailObj) {
        self.kalista = kalista
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kalista = "Kalista"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kalista, forKey: .kalista)
    }
}

