//
// KarmaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KarmaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var karma: ChampionDetailObj

    public init(karma: ChampionDetailObj) {
        self.karma = karma
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case karma = "Karma"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(karma, forKey: .karma)
    }
}

