//
// KarthusChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KarthusChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var karthus: ChampionDetailObj

    public init(karthus: ChampionDetailObj) {
        self.karthus = karthus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case karthus = "Karthus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(karthus, forKey: .karthus)
    }
}

