//
// KassadinChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KassadinChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kassadin: ChampionDetailObj

    public init(kassadin: ChampionDetailObj) {
        self.kassadin = kassadin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kassadin = "Kassadin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kassadin, forKey: .kassadin)
    }
}

