//
// KayleChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KayleChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kayle: ChampionDetailObj

    public init(kayle: ChampionDetailObj) {
        self.kayle = kayle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kayle = "Kayle"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kayle, forKey: .kayle)
    }
}

