//
// KennenChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KennenChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kennen: ChampionDetailObj

    public init(kennen: ChampionDetailObj) {
        self.kennen = kennen
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kennen = "Kennen"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kennen, forKey: .kennen)
    }
}

