//
// KindredChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KindredChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kindred: ChampionDetailObj

    public init(kindred: ChampionDetailObj) {
        self.kindred = kindred
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kindred = "Kindred"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kindred, forKey: .kindred)
    }
}

