//
// KledChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KledChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kled: ChampionDetailObj

    public init(kled: ChampionDetailObj) {
        self.kled = kled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kled = "Kled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kled, forKey: .kled)
    }
}

