//
// KogMawChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KogMawChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var kogMaw: ChampionDetailObj

    public init(kogMaw: ChampionDetailObj) {
        self.kogMaw = kogMaw
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kogMaw = "KogMaw"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kogMaw, forKey: .kogMaw)
    }
}

