//
// LeblancChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeblancChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var leblanc: ChampionDetailObj

    public init(leblanc: ChampionDetailObj) {
        self.leblanc = leblanc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leblanc = "Leblanc"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(leblanc, forKey: .leblanc)
    }
}

