//
// LeeSinChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeeSinChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var leeSin: ChampionDetailObj

    public init(leeSin: ChampionDetailObj) {
        self.leeSin = leeSin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leeSin = "LeeSin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(leeSin, forKey: .leeSin)
    }
}

