//
// LeonaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeonaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var leona: ChampionDetailObj

    public init(leona: ChampionDetailObj) {
        self.leona = leona
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leona = "Leona"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(leona, forKey: .leona)
    }
}

