//
// LevelTipObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LevelTipObj: Codable, JSONEncodable, Hashable {

    public var label: [String]
    public var effect: [String]

    public init(label: [String], effect: [String]) {
        self.label = label
        self.effect = effect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case effect
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(effect, forKey: .effect)
    }
}

