//
// LilliaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LilliaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var lillia: ChampionDetailObj

    public init(lillia: ChampionDetailObj) {
        self.lillia = lillia
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lillia = "Lillia"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lillia, forKey: .lillia)
    }
}

