//
// LissandraChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LissandraChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var lissandra: ChampionDetailObj

    public init(lissandra: ChampionDetailObj) {
        self.lissandra = lissandra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lissandra = "Lissandra"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lissandra, forKey: .lissandra)
    }
}

