//
// MalphiteChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MalphiteChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var malphite: ChampionDetailObj

    public init(malphite: ChampionDetailObj) {
        self.malphite = malphite
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malphite = "Malphite"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(malphite, forKey: .malphite)
    }
}

