//
// MalzaharChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MalzaharChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var malzahar: ChampionDetailObj

    public init(malzahar: ChampionDetailObj) {
        self.malzahar = malzahar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case malzahar = "Malzahar"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(malzahar, forKey: .malzahar)
    }
}

