//
// MaokaiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MaokaiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var maokai: ChampionDetailObj

    public init(maokai: ChampionDetailObj) {
        self.maokai = maokai
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maokai = "Maokai"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(maokai, forKey: .maokai)
    }
}

