//
// MasterYiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MasterYiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var masterYi: ChampionDetailObj

    public init(masterYi: ChampionDetailObj) {
        self.masterYi = masterYi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case masterYi = "MasterYi"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(masterYi, forKey: .masterYi)
    }
}

