//
// MordekaiserChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MordekaiserChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var mordekaiser: ChampionDetailObj

    public init(mordekaiser: ChampionDetailObj) {
        self.mordekaiser = mordekaiser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mordekaiser = "Mordekaiser"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mordekaiser, forKey: .mordekaiser)
    }
}

