//
// MorganaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MorganaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var morgana: ChampionDetailObj

    public init(morgana: ChampionDetailObj) {
        self.morgana = morgana
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case morgana = "Morgana"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(morgana, forKey: .morgana)
    }
}

