//
// NamiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NamiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var nami: ChampionDetailObj

    public init(nami: ChampionDetailObj) {
        self.nami = nami
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nami = "Nami"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nami, forKey: .nami)
    }
}

