//
// NeekoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NeekoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var neeko: ChampionDetailObj

    public init(neeko: ChampionDetailObj) {
        self.neeko = neeko
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case neeko = "Neeko"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(neeko, forKey: .neeko)
    }
}

