//
// NilahChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NilahChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var nilah: ChampionDetailObj

    public init(nilah: ChampionDetailObj) {
        self.nilah = nilah
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nilah = "Nilah"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nilah, forKey: .nilah)
    }
}

