//
// NocturneChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NocturneChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var nocturne: ChampionDetailObj

    public init(nocturne: ChampionDetailObj) {
        self.nocturne = nocturne
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nocturne = "Nocturne"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nocturne, forKey: .nocturne)
    }
}

