//
// OlafChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OlafChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var olaf: ChampionDetailObj

    public init(olaf: ChampionDetailObj) {
        self.olaf = olaf
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case olaf = "Olaf"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(olaf, forKey: .olaf)
    }
}

