//
// PantheonChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PantheonChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var pantheon: ChampionDetailObj

    public init(pantheon: ChampionDetailObj) {
        self.pantheon = pantheon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pantheon = "Pantheon"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pantheon, forKey: .pantheon)
    }
}

