//
// PoppyChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PoppyChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var poppy: ChampionDetailObj

    public init(poppy: ChampionDetailObj) {
        self.poppy = poppy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case poppy = "Poppy"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(poppy, forKey: .poppy)
    }
}

