//
// PykeChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PykeChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var pyke: ChampionDetailObj

    public init(pyke: ChampionDetailObj) {
        self.pyke = pyke
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pyke = "Pyke"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pyke, forKey: .pyke)
    }
}

