//
// QiyanaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QiyanaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var qiyana: ChampionDetailObj

    public init(qiyana: ChampionDetailObj) {
        self.qiyana = qiyana
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case qiyana = "Qiyana"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(qiyana, forKey: .qiyana)
    }
}

