//
// RakanChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RakanChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var rakan: ChampionDetailObj

    public init(rakan: ChampionDetailObj) {
        self.rakan = rakan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rakan = "Rakan"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rakan, forKey: .rakan)
    }
}

