//
// RammusChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RammusChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var rammus: ChampionDetailObj

    public init(rammus: ChampionDetailObj) {
        self.rammus = rammus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rammus = "Rammus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rammus, forKey: .rammus)
    }
}

