//
// RellChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RellChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var rell: ChampionDetailObj

    public init(rell: ChampionDetailObj) {
        self.rell = rell
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rell = "Rell"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rell, forKey: .rell)
    }
}

