//
// RenataChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenataChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var renata: ChampionDetailObj

    public init(renata: ChampionDetailObj) {
        self.renata = renata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renata = "Renata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renata, forKey: .renata)
    }
}

