//
// RenektonChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RenektonChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var renekton: ChampionDetailObj

    public init(renekton: ChampionDetailObj) {
        self.renekton = renekton
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case renekton = "Renekton"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(renekton, forKey: .renekton)
    }
}

