//
// RengarChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RengarChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var rengar: ChampionDetailObj

    public init(rengar: ChampionDetailObj) {
        self.rengar = rengar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rengar = "Rengar"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rengar, forKey: .rengar)
    }
}

