//
// RumbleChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RumbleChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var rumble: ChampionDetailObj

    public init(rumble: ChampionDetailObj) {
        self.rumble = rumble
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rumble = "Rumble"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rumble, forKey: .rumble)
    }
}

