//
// RuneObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RuneObj: Codable, JSONEncodable, Hashable {

    public var id: Double
    public var key: String
    public var icon: String
    public var name: String
    public var slots: [RuneObjSlotsInner]

    public init(id: Double, key: String, icon: String, name: String, slots: [RuneObjSlotsInner]) {
        self.id = id
        self.key = key
        self.icon = icon
        self.name = name
        self.slots = slots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case icon
        case name
        case slots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(key, forKey: .key)
        try container.encode(icon, forKey: .icon)
        try container.encode(name, forKey: .name)
        try container.encode(slots, forKey: .slots)
    }
}

