//
// RyzeChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RyzeChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var ryze: ChampionDetailObj

    public init(ryze: ChampionDetailObj) {
        self.ryze = ryze
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ryze = "Ryze"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ryze, forKey: .ryze)
    }
}

