//
// SamiraChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SamiraChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var samira: ChampionDetailObj

    public init(samira: ChampionDetailObj) {
        self.samira = samira
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case samira = "Samira"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(samira, forKey: .samira)
    }
}

