//
// SejuaniChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SejuaniChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var sejuani: ChampionDetailObj

    public init(sejuani: ChampionDetailObj) {
        self.sejuani = sejuani
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sejuani = "Sejuani"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sejuani, forKey: .sejuani)
    }
}

