//
// SennaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SennaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var senna: ChampionDetailObj

    public init(senna: ChampionDetailObj) {
        self.senna = senna
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case senna = "Senna"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(senna, forKey: .senna)
    }
}

