//
// SeraphineChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SeraphineChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var seraphine: ChampionDetailObj

    public init(seraphine: ChampionDetailObj) {
        self.seraphine = seraphine
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seraphine = "Seraphine"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seraphine, forKey: .seraphine)
    }
}

