//
// ShacoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShacoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var shaco: ChampionDetailObj

    public init(shaco: ChampionDetailObj) {
        self.shaco = shaco
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shaco = "Shaco"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shaco, forKey: .shaco)
    }
}

