//
// ShyvanaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShyvanaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var shyvana: ChampionDetailObj

    public init(shyvana: ChampionDetailObj) {
        self.shyvana = shyvana
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shyvana = "Shyvana"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shyvana, forKey: .shyvana)
    }
}

