//
// SivirChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SivirChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var sivir: ChampionDetailObj

    public init(sivir: ChampionDetailObj) {
        self.sivir = sivir
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sivir = "Sivir"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sivir, forKey: .sivir)
    }
}

