//
// SkarnerChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SkarnerChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var skarner: ChampionDetailObj

    public init(skarner: ChampionDetailObj) {
        self.skarner = skarner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case skarner = "Skarner"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(skarner, forKey: .skarner)
    }
}

