//
// SorakaChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SorakaChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var soraka: ChampionDetailObj

    public init(soraka: ChampionDetailObj) {
        self.soraka = soraka
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case soraka = "Soraka"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(soraka, forKey: .soraka)
    }
}

