//
// TaliyahChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaliyahChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var taliyah: ChampionDetailObj

    public init(taliyah: ChampionDetailObj) {
        self.taliyah = taliyah
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taliyah = "Taliyah"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(taliyah, forKey: .taliyah)
    }
}

