//
// TaricChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaricChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var taric: ChampionDetailObj

    public init(taric: ChampionDetailObj) {
        self.taric = taric
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taric = "Taric"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(taric, forKey: .taric)
    }
}

