//
// TeemoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TeemoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var teemo: ChampionDetailObj

    public init(teemo: ChampionDetailObj) {
        self.teemo = teemo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teemo = "Teemo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(teemo, forKey: .teemo)
    }
}

