//
// ThreshChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ThreshChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var thresh: ChampionDetailObj

    public init(thresh: ChampionDetailObj) {
        self.thresh = thresh
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case thresh = "Thresh"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(thresh, forKey: .thresh)
    }
}

