//
// TrundleChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrundleChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var trundle: ChampionDetailObj

    public init(trundle: ChampionDetailObj) {
        self.trundle = trundle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trundle = "Trundle"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(trundle, forKey: .trundle)
    }
}

