//
// TwistedFateChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TwistedFateChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var twistedFate: ChampionDetailObj

    public init(twistedFate: ChampionDetailObj) {
        self.twistedFate = twistedFate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case twistedFate = "TwistedFate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(twistedFate, forKey: .twistedFate)
    }
}

