//
// TwitchChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TwitchChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var twitch: ChampionDetailObj

    public init(twitch: ChampionDetailObj) {
        self.twitch = twitch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case twitch = "Twitch"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(twitch, forKey: .twitch)
    }
}

