//
// UdyrChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UdyrChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var udyr: ChampionDetailObj

    public init(udyr: ChampionDetailObj) {
        self.udyr = udyr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case udyr = "Udyr"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(udyr, forKey: .udyr)
    }
}

