//
// UrgotChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UrgotChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var urgot: ChampionDetailObj

    public init(urgot: ChampionDetailObj) {
        self.urgot = urgot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urgot = "Urgot"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(urgot, forKey: .urgot)
    }
}

