//
// VarusChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VarusChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var varus: ChampionDetailObj

    public init(varus: ChampionDetailObj) {
        self.varus = varus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case varus = "Varus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(varus, forKey: .varus)
    }
}

