//
// VayneChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VayneChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var vayne: ChampionDetailObj

    public init(vayne: ChampionDetailObj) {
        self.vayne = vayne
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vayne = "Vayne"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vayne, forKey: .vayne)
    }
}

