//
// VelkozChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VelkozChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var velkoz: ChampionDetailObj

    public init(velkoz: ChampionDetailObj) {
        self.velkoz = velkoz
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case velkoz = "Velkoz"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(velkoz, forKey: .velkoz)
    }
}

