//
// ViChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ViChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var vi: ChampionDetailObj

    public init(vi: ChampionDetailObj) {
        self.vi = vi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vi = "Vi"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vi, forKey: .vi)
    }
}

