//
// VladimirChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VladimirChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var vladimir: ChampionDetailObj

    public init(vladimir: ChampionDetailObj) {
        self.vladimir = vladimir
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vladimir = "Vladimir"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vladimir, forKey: .vladimir)
    }
}

