//
// WarwickChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WarwickChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var warwick: ChampionDetailObj

    public init(warwick: ChampionDetailObj) {
        self.warwick = warwick
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warwick = "Warwick"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(warwick, forKey: .warwick)
    }
}

