//
// XayahChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct XayahChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var xayah: ChampionDetailObj

    public init(xayah: ChampionDetailObj) {
        self.xayah = xayah
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case xayah = "Xayah"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(xayah, forKey: .xayah)
    }
}

