//
// XerathChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct XerathChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var xerath: ChampionDetailObj

    public init(xerath: ChampionDetailObj) {
        self.xerath = xerath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case xerath = "Xerath"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(xerath, forKey: .xerath)
    }
}

