//
// XinZhaoChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct XinZhaoChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var xinZhao: ChampionDetailObj

    public init(xinZhao: ChampionDetailObj) {
        self.xinZhao = xinZhao
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case xinZhao = "XinZhao"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(xinZhao, forKey: .xinZhao)
    }
}

