//
// YoneChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct YoneChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var yone: ChampionDetailObj

    public init(yone: ChampionDetailObj) {
        self.yone = yone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case yone = "Yone"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(yone, forKey: .yone)
    }
}

