//
// YuumiChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct YuumiChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var yuumi: ChampionDetailObj

    public init(yuumi: ChampionDetailObj) {
        self.yuumi = yuumi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case yuumi = "Yuumi"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(yuumi, forKey: .yuumi)
    }
}

