//
// ZacChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZacChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var zac: ChampionDetailObj

    public init(zac: ChampionDetailObj) {
        self.zac = zac
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zac = "Zac"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zac, forKey: .zac)
    }
}

