//
// ZedChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZedChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var zed: ChampionDetailObj

    public init(zed: ChampionDetailObj) {
        self.zed = zed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zed = "Zed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zed, forKey: .zed)
    }
}

