//
// ZiggsChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZiggsChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var ziggs: ChampionDetailObj

    public init(ziggs: ChampionDetailObj) {
        self.ziggs = ziggs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ziggs = "Ziggs"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ziggs, forKey: .ziggs)
    }
}

