//
// ZileanChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZileanChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var zilean: ChampionDetailObj

    public init(zilean: ChampionDetailObj) {
        self.zilean = zilean
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zilean = "Zilean"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zilean, forKey: .zilean)
    }
}

