//
// ZoeChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZoeChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var zoe: ChampionDetailObj

    public init(zoe: ChampionDetailObj) {
        self.zoe = zoe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zoe = "Zoe"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zoe, forKey: .zoe)
    }
}

