//
// ZyraChampionDetailObj.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ZyraChampionDetailObj: Codable, JSONEncodable, Hashable {

    public var zyra: ChampionDetailObj

    public init(zyra: ChampionDetailObj) {
        self.zyra = zyra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zyra = "Zyra"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zyra, forKey: .zyra)
    }
}

