//
// DataSummonerNameAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DataSummonerNameAPI {

    /**
     Data List
     
     - parameter summonerName: (path) version 
     - parameter apiKey: (query) api_key 
     - returns: SummonerByName
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDataSummonerName(summonerName: String, apiKey: String) async throws -> SummonerByName {
        return try await getDataSummonerNameWithRequestBuilder(summonerName: summonerName, apiKey: apiKey).execute().body
    }

    /**
     Data List
     - GET /lol/summoner/v4/summoners/by-name/{summonerName}
     - parameter summonerName: (path) version 
     - parameter apiKey: (query) api_key 
     - returns: RequestBuilder<SummonerByName> 
     */
    open class func getDataSummonerNameWithRequestBuilder(summonerName: String, apiKey: String) -> RequestBuilder<SummonerByName> {
        var localVariablePath = "/lol/summoner/v4/summoners/by-name/{summonerName}"
        let summonerNamePreEscape = "\(APIHelper.mapValueToPathItem(summonerName))"
        let summonerNamePostEscape = summonerNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{summonerName}", with: summonerNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "api_key": (wrappedValue: apiKey.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SummonerByName>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
