//
// DataMatchInfoAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DataMatchInfoAPI {

    /**
     Data List
     
     - parameter matchId: (path) version 
     - parameter apiKey: (query) api_key 
     - returns: ModelMatchInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDataMatchInfo(matchId: String, apiKey: String) async throws -> ModelMatchInfo {
        return try await getDataMatchInfoWithRequestBuilder(matchId: matchId, apiKey: apiKey).execute().body
    }

    /**
     Data List
     - GET /lol/match/v5/matches/{matchId}
     - parameter matchId: (path) version 
     - parameter apiKey: (query) api_key 
     - returns: RequestBuilder<ModelMatchInfo> 
     */
    open class func getDataMatchInfoWithRequestBuilder(matchId: String, apiKey: String) -> RequestBuilder<ModelMatchInfo> {
        var localVariablePath = "/lol/match/v5/matches/{matchId}"
        let matchIdPreEscape = "\(APIHelper.mapValueToPathItem(matchId))"
        let matchIdPostEscape = matchIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{matchId}", with: matchIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "api_key": (wrappedValue: apiKey.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ModelMatchInfo>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
