//
// ModelMatchInfoInfoParticipantsInnerPerksStylesInnerSelectionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoInfoParticipantsInnerPerksStylesInnerSelectionsInner: Codable, JSONEncodable, Hashable {

    public var perk: Double?
    public var var1: Double?
    public var var2: Double?
    public var var3: Double?

    public init(perk: Double? = nil, var1: Double? = nil, var2: Double? = nil, var3: Double? = nil) {
        self.perk = perk
        self.var1 = var1
        self.var2 = var2
        self.var3 = var3
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case perk
        case var1
        case var2
        case var3
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(perk, forKey: .perk)
        try container.encodeIfPresent(var1, forKey: .var1)
        try container.encodeIfPresent(var2, forKey: .var2)
        try container.encodeIfPresent(var3, forKey: .var3)
    }
}

