//
// ModelMatchInfoInfoParticipantsInnerPerksStylesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoInfoParticipantsInnerPerksStylesInner: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var selections: [ModelMatchInfoInfoParticipantsInnerPerksStylesInnerSelectionsInner]?
    public var style: Double?

    public init(description: String? = nil, selections: [ModelMatchInfoInfoParticipantsInnerPerksStylesInnerSelectionsInner]? = nil, style: Double? = nil) {
        self.description = description
        self.selections = selections
        self.style = style
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case selections
        case style
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(selections, forKey: .selections)
        try container.encodeIfPresent(style, forKey: .style)
    }
}

