//
// ModelMatchInfoMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoMetadata: Codable, JSONEncodable, Hashable {

    public var dataVersion: String
    public var matchId: String
    public var participants: [String]

    public init(dataVersion: String, matchId: String, participants: [String]) {
        self.dataVersion = dataVersion
        self.matchId = matchId
        self.participants = participants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataVersion
        case matchId
        case participants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dataVersion, forKey: .dataVersion)
        try container.encode(matchId, forKey: .matchId)
        try container.encode(participants, forKey: .participants)
    }
}

