//
// ModelMatchInfoInfoTeamsInnerObjectivesBaron.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoInfoTeamsInnerObjectivesBaron: Codable, JSONEncodable, Hashable {

    public var first: Bool
    public var kills: Double

    public init(first: Bool, kills: Double) {
        self.first = first
        self.kills = kills
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case kills
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(first, forKey: .first)
        try container.encode(kills, forKey: .kills)
    }
}

