//
// ModelMatchInfoInfoParticipantsInnerPerks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoInfoParticipantsInnerPerks: Codable, JSONEncodable, Hashable {

    public var statPerks: ModelMatchInfoInfoParticipantsInnerPerksStatPerks
    public var styles: [ModelMatchInfoInfoParticipantsInnerPerksStylesInner]

    public init(statPerks: ModelMatchInfoInfoParticipantsInnerPerksStatPerks, styles: [ModelMatchInfoInfoParticipantsInnerPerksStylesInner]) {
        self.statPerks = statPerks
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statPerks
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(statPerks, forKey: .statPerks)
        try container.encode(styles, forKey: .styles)
    }
}

