//
// ModelMatchInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfo: Codable, JSONEncodable, Hashable,Identifiable {
    public var id: UUID = .init()
    public var metadata: ModelMatchInfoMetadata
    public var info: ModelMatchInfoInfo

    public init(metadata: ModelMatchInfoMetadata, info: ModelMatchInfoInfo) {
        self.metadata = metadata
        self.info = info
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadata
        case info
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(info, forKey: .info)
    }
}

