//
// ModelMatchInfoInfoParticipantsInnerPerksStatPerks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelMatchInfoInfoParticipantsInnerPerksStatPerks: Codable, JSONEncodable, Hashable {

    public var defense: Double
    public var flex: Double
    public var offense: Double

    public init(defense: Double, flex: Double, offense: Double) {
        self.defense = defense
        self.flex = flex
        self.offense = offense
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defense
        case flex
        case offense
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(defense, forKey: .defense)
        try container.encode(flex, forKey: .flex)
        try container.encode(offense, forKey: .offense)
    }
}

