//
// DetailRunesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DetailRunesAPI {

    /**
     Runes
     
     - parameter version: (path) version 
     - parameter localization: (path) localization 
     - returns: [RuneObj]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRunes(version: String, localization: String) async throws -> [RuneObj] {
        return try await getRunesWithRequestBuilder(version: version, localization: localization).execute().body
    }

    /**
     Runes
     - GET /cdn/{version}/data/{localization}/runesReforged.json
     - parameter version: (path) version 
     - parameter localization: (path) localization 
     - returns: RequestBuilder<[RuneObj]> 
     */
    open class func getRunesWithRequestBuilder(version: String, localization: String) -> RequestBuilder<[RuneObj]> {
        var localVariablePath = "/cdn/{version}/data/{localization}/runesReforged.json"
        let versionPreEscape = "\(APIHelper.mapValueToPathItem(version))"
        let versionPostEscape = versionPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{version}", with: versionPostEscape, options: .literal, range: nil)
        let localizationPreEscape = "\(APIHelper.mapValueToPathItem(localization))"
        let localizationPostEscape = localizationPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{localization}", with: localizationPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RuneObj]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
